# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('prescription', models.ImageField(upload_to='')),
                ('address_street', models.TextField()),
                ('address_city', models.CharField(max_length=20)),
                ('address_state', models.CharField(max_length=20)),
                ('address_pincode', models.IntegerField()),
                ('delivered_date', models.DateField()),
            ],
        ),
    ]
