# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('otc_or_not', models.BooleanField()),
                ('brand_name', models.CharField(max_length=50)),
                ('salts', models.TextField()),
                ('specifications', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
