# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('prescription', models.ImageField(upload_to='')),
                ('address_street', models.TextField()),
                ('address_city', models.CharField(max_length=20)),
                ('address_state', models.CharField(max_length=20)),
                ('address_pincode', models.IntegerField()),
                ('delivered_date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy')),
            ],
        ),
    ]
