# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='pharmacy_notifications',
        ),
    ]
